/* AUTO-GENERATED 2025-07-02T02:05:14 */
#include "Port_Cfg.h"

static const Port_PinConfigType Port_PinConfigs[] = {
	// POWER SUPPLY PINS CN7 IOs
    {GPIOA, GPIO_PIN_1, PORT_PIN_MODE_ANALOG, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PA1 : ADC123_IN1
    {GPIOA, GPIO_PIN_4, PORT_PIN_MODE_ANALOG, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PA4 : ADC12_IN4

	// DIGITAL OUTPUT PINS CN10 IOs
	{GPIOA, GPIO_PIN_5, PORT_PIN_MODE_GPIO, PORT_PIN_OUT, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW},  // PA5  : Washer (G LED)
//	{GPIOC, GPIO_PIN_10, PORT_PIN_MODE_GPIO, PORT_PIN_OUT, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC10 : High Beam
//	{GPIOC, GPIO_PIN_11, PORT_PIN_MODE_GPIO, PORT_PIN_OUT, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC11 : Washer
//	{GPIOC, GPIO_PIN_12, PORT_PIN_MODE_GPIO, PORT_PIN_OUT, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC12 :

	// DIGITAL INPUT PINS CN10 IOs
	{GPIOC, GPIO_PIN_13, PORT_PIN_MODE_GPIO, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC13 : High Beam Btn
	{GPIOC, GPIO_PIN_14, PORT_PIN_MODE_GPIO, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC14 : Low Beam Btn
	{GPIOC, GPIO_PIN_15, PORT_PIN_MODE_GPIO, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC15 : Washer Btn
//	{GPIOH, GPIO_PIN_0, PORT_PIN_MODE_GPIO, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW},	 // PH0  :

	// PWM OUTPUT PINS CN10 IOs
	{GPIOB, GPIO_PIN_4, PORT_PIN_MODE_AF2, PORT_PIN_OUT, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PB4 : TIM3_CH1 HBeam Out
	{GPIOB, GPIO_PIN_5, PORT_PIN_MODE_AF2, PORT_PIN_OUT, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PB5 : TIM3_CH2 LBeam Out
	{GPIOC, GPIO_PIN_8, PORT_PIN_MODE_AF2, PORT_PIN_OUT, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC8 : TIM3_CH3 Wiper Out

	// ANALOG INPUT PINS CN7 IOs
	{GPIOC, GPIO_PIN_2, PORT_PIN_MODE_ANALOG, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC2 : ADC123_IN12 : Wiper In
	{GPIOC, GPIO_PIN_3, PORT_PIN_MODE_ANALOG, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC3 : ADC123_IN13 : Engin Temp
	{GPIOC, GPIO_PIN_4, PORT_PIN_MODE_ANALOG, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC4 : ADC12_IN14 : Oil Press
	{GPIOC, GPIO_PIN_5, PORT_PIN_MODE_ANALOG, PORT_PIN_IN, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW}, // PC5 : ADC12_IN15 : BAtt Volt

};

const Port_ConfigType Port_Config = {
    .PinCfgArr = Port_PinConfigs,
    .NumPins   = 13u
};
