/*
 * Fvr_cfg.c
 *
 *  Created on: Nov 2, 2025
 *      Author: Lenovo X13
 */


#include "Fvr_cfg.h"
#include "Iom_Cfg.h"
#include "Adm.h"
#include "Pmm.h"

const uint8_t fvr_out_channels[FVR_NUM_OUT_CHANNELS] = {IOM_CH_INTERNAL_GREEN_LED, IOM_CH_HVAC_FAN, IOM_CH_RIGHT_TURN_INDICATOR, IOM_CH_LEFT_TURN_INDICATOR, // TOR OUT
														PMM_HEAD_LAMPS_HIGH_BEAM, PMM_HEAD_LAMPS_LOW_BEAM, PMM_RIGHT_TI, PMM_LEFT_TI};// PWM OUT


const uint8_t fvr_in_channels[FVR_NUM_IN_CHANNELS] = {IOM_CH_FRONT_RIGHT_WINDOW_BUTTON, IOM_CH_FRONT_LEFT_WINDOW_BUTTON, IOM_CH_BACK_RIGHT_WINDOW_BUTTON, IOM_CH_BACK_LEFT_WINDOW_BUTTON, // DIN
													ADM_TEMPERATURE_SENSOR_CHANNEL, ADM_LUMINOSITY_SENSOR_CHANNEL}; // AIN


const uint8_t fvr_out_action[FVR_NUM_OUT_CHANNELS][FVR_NUM_OF_VALID_RANGES] = {
		{FVR_OFF, FVR_OPERATIONEL, FVR_OFF, FVR_OFF},
		{FVR_OFF, FVR_OPERATIONEL, FVR_OFF, FVR_OFF},
		{FVR_OFF, FVR_OPERATIONEL, FVR_OFF, FVR_OFF},
		{FVR_OFF, FVR_OPERATIONEL, FVR_OFF, FVR_OFF},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OFF, FVR_OPERATIONEL, FVR_OFF, FVR_OFF},
		{FVR_OFF, FVR_OPERATIONEL, FVR_OFF, FVR_OFF},
		{FVR_OFF, FVR_OPERATIONEL, FVR_OFF, FVR_OFF}
};

const uint8_t fvr_in_action[FVR_NUM_IN_CHANNELS][FVR_NUM_OF_VALID_RANGES] = {
		{FVR_OFF, FVR_OPERATIONEL, FVR_IGNORED, FVR_IGNORED},
		{FVR_OFF, FVR_OPERATIONEL, FVR_IGNORED, FVR_IGNORED},
		{FVR_OFF, FVR_OPERATIONEL, FVR_IGNORED, FVR_IGNORED},
		{FVR_OFF, FVR_OPERATIONEL, FVR_IGNORED, FVR_IGNORED},
		{FVR_OFF, FVR_OPERATIONEL, FVR_IGNORED, FVR_IGNORED},
		{FVR_OFF, FVR_OPERATIONEL, FVR_IGNORED, FVR_IGNORED}
};


