/*
 * Fvr_cfg.c
 *
 *  Created on: Nov 2, 2025
 *      Author: Lenovo X13
 */


#include "Fvr_cfg.h"
#include "Fvr.h"


const uint8_t fvr_out_channels[FVR_NUM_OUT_CHANNELS] = {FVR_WASHER_OUT_CHANNLE, // TOR OUT
		FVR_HIGH_BEAM_OUT_CHANNLE, FVR_LOW_BEAM_OUT_CHANNLE, FVR_WIPER_OUT_CHANNLE};// PWM OUT


const uint8_t fvr_in_channels[FVR_NUM_IN_CHANNELS] = {FVR_HIGH_BEAM_IN_CHANNLE, FVR_LOW_BEAM_IN_CHANNLE, FVR_WASHER_IN_CHANNLE, // DIN
													  FVR_ENGINE_TEMPERATURE_CHANNEL, FVR_OIL_PRESSURE_CHANNEL, FVR_BATTERY_VOLTAGE_CHANNEL, FVR_WIPER_LEVEL_CHANNEL, FVR_WIPER_POSITION_CHANNEL}; // AIN


const uint8_t fvr_out_action[FVR_NUM_OUT_CHANNELS][FVR_NUM_OF_VALID_RANGES] = {
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL}
};

const uint8_t fvr_in_action[FVR_NUM_IN_CHANNELS][FVR_NUM_OF_VALID_RANGES] = {
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
		{FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL, FVR_OPERATIONEL},
};


